import bcrypt from 'bcryptjs'

const data = {
  users: [
    {
      firstName: 'Daniel',
      staffId: 'DV00001',
      lastName: 'Ello',
      email: 'demakventures@gmail.com',
      password: bcrypt.hashSync('demak@1234'),
      isAdmin: true,
    },
    {
      firstName: 'Matthew',
      staffId: 'DV00025',
      lastName: 'Domi',
      email: 'demakventures1@gmail.com',
      password: bcrypt.hashSync('demak@1234'),
      isAdmin: false,
    },
    {
      firstName: 'Bless',
      staffId: 'DV00020',
      lastName: 'Anku',
      email: 'demakventures2@gmail.com',
      password: bcrypt.hashSync('demak@1234'),
      isAdmin: false,
    },
    {
      firstName: 'Benedicta',
      staffId: 'DV00015',
      lastName: 'Gbedema',
      email: 'demakventures3@gmail.com',
      password: bcrypt.hashSync('demak@1234'),
      isAdmin: false,
    },
    {
      firstName: 'Eric',
      staffId: 'DV00010',
      lastName: 'Anagbonu',
      email: 'demakventures4@gmail.com',
      password: bcrypt.hashSync('demak@1234'),
      isAdmin: false,
    },
    {
      firstName: 'Daniel',
      staffId: 'DV0005',
      lastName: 'Amada',
      email: 'demakventures5@gmail.com',
      password: bcrypt.hashSync('demak@1234'),
      isAdmin: false,
    },
    {
      firstName: 'Gloria',
      staffId: 'DV00091',
      lastName: 'Anagbonu',
      email: 'demakventures6@gmail.com',
      password: bcrypt.hashSync('demak@1234'),
      isAdmin: true,
    },
    {
      firstName: 'Kingsbeth',
      staffId: 'DV0075',
      lastName: 'Midodzi',
      email: 'demakventures7@gmail.com',
      password: bcrypt.hashSync('demak@1234'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Shirt',
      slug: 'free-shirt',
      category: 'products',
      image: '/public/images/1.jpg',
      price: 70,
      brand: 'Polo',
      rating: 4.5,
      numReviews: 7,
      countInStock: 7,
      description: 'A Well Popular Shirt',
    },
    {
      name: 'Sandals',
      slug: 'free-Sandals',
      category: 'products',
      image: '/public/images/2.jpg',
      price: 70,
      brand: 'Polo',
      rating: 4.5,
      numReviews: 7,
      countInStock: 7,
      description: 'A Well Popular Sandals',
    },
    {
      name: 'Shoe',
      slug: 'free-Shoe',
      category: 'products',
      image: '/public/images/6.jpg',
      price: 70,
      brand: 'Polo',
      rating: 4.5,
      numReviews: 7,
      countInStock: 7,
      description: 'A Well Popular Shoe',
    },
    {
      name: 'Leather',
      slug: 'free-Leather',
      category: 'products',
      image: '/public/images/5.jpg',
      price: 70,
      brand: 'Polo',
      rating: 4.5,
      numReviews: 7,
      countInStock: 7,
      description: 'A Well Popular Leather',
    },
    {
      name: 'Bag',
      slug: 'free-Bag',
      category: 'products',
      image: '/public/images/6.jpg',
      price: 70,
      brand: 'Polo',
      rating: 4.5,
      numReviews: 7,
      countInStock: 7,
      description: 'A Well Popular Bag',
    },
    {
      name: 'Shirt',
      slug: 'free-shirt1',
      category: 'products',
      image: '/public/images/7.jpg',
      price: 70,
      brand: 'Polo',
      rating: 4.5,
      numReviews: 7,
      countInStock: 7,
      description: 'A Well Popular Shirt',
    },
    {
      name: 'Shirt',
      slug: 'free-shirt2',
      category: 'products',
      image: '/public/images/8.jpg',
      price: 70,
      brand: 'Polo',
      rating: 4.5,
      numReviews: 7,
      countInStock: 7,
      description: 'A Well Popular Shirt',
    },
    {
      name: 'Shirt',
      slug: 'free-shirt3',
      category: 'products',
      image: '/public/images/9.jpg',
      price: 70,
      brand: 'Polo',
      rating: 4.5,
      numReviews: 7,
      countInStock: 7,
      description: 'A Well Popular Shirt',
    },
    {
      name: 'Shirt',
      slug: 'free-shirt4',
      category: 'products',
      image: '/public/images/1.jpg',
      price: 70,
      brand: 'Polo',
      rating: 4.5,
      numReviews: 7,
      countInStock: 7,
      description: 'A Well Popular Shirt',
    },
    {
      name: 'Shirt',
      slug: 'free-shirt5',
      category: 'products',
      image: '/public/images/1.jpg',
      price: 70,
      brand: 'Polo',
      rating: 4.5,
      numReviews: 7,
      countInStock: 7,
      description: 'A Well Popular Shirt',
    },
    {
      name: 'Shirt',
      slug: 'free-shirt6',
      category: 'products',
      image: '/public/images/2.jpg',
      price: 70,
      brand: 'Polo',
      rating: 4.5,
      numReviews: 7,
      countInStock: 7,
      description: 'A Well Popular Shirt',
    },
    {
      name: 'Shirt',
      slug: 'free-shirt7',
      category: 'products',
      image: '/public/images/1.jpg',
      price: 70,
      brand: 'Polo',
      rating: 4.5,
      numReviews: 7,
      countInStock: 7,
      description: 'A Well Popular Shirt',
    },
    {
      name: 'Shirt',
      slug: 'free-shirt8',
      category: 'products',
      image: '/public/images/3.jpg',
      price: 70,
      brand: 'Polo',
      rating: 4.5,
      numReviews: 7,
      countInStock: 7,
      description: 'A Well Popular Shirt',
    },
    {
      name: 'Shirt',
      slug: 'free-shirt9',
      category: 'products',
      image: '/public/images/4.jpg',
      price: 70,
      brand: 'Polo',
      rating: 4.5,
      numReviews: 7,
      countInStock: 7,
      description: 'A Well Popular Shirt',
    },
    {
      name: 'Shirt',
      slug: 'free-shirt10',
      category: 'products',
      image: '/public/images/5.jpg',
      price: 70,
      brand: 'Polo',
      rating: 4.5,
      numReviews: 7,
      countInStock: 7,
      description: 'A Well Popular Shirt',
    },
    {
      name: 'Shirt',
      slug: 'free-shirt11',
      category: 'products',
      image: '/public/images/6.jpg',
      price: 70,
      brand: 'Polo',
      rating: 4.5,
      numReviews: 7,
      countInStock: 7,
      description: 'A Well Popular Shirt',
    },

    {
      name: 'Shirt',
      slug: 'free-shirt12',
      category: 'products',
      image: '/public/images/7.jpg',
      price: 70,
      brand: 'Polo',
      rating: 4.5,
      numReviews: 7,
      countInStock: 7,
      description: 'A Well Popular Shirt',
    },
    {
      name: 'Shirt',
      slug: 'free-shirt13',
      category: 'products',
      image: '/public/images/8.jpg',
      price: 70,
      brand: 'Polo',
      rating: 4.5,
      numReviews: 7,
      countInStock: 7,
      description: 'A Well Popular Shirt',
    },
    {
      name: 'Shirt',
      slug: 'free-shirt14',
      category: 'products',
      image: '/public/images/9.jpg',
      price: 70,
      brand: 'Polo',
      rating: 4.5,
      numReviews: 7,
      countInStock: 7,
      description: 'A Well Popular Shirt',
    },

    {
      name: 'Shirt',
      slug: 'free-shirt15',
      category: 'products',
      image: '/public/images/1.jpg',
      price: 70,
      brand: 'Polo',
      rating: 4.5,
      numReviews: 7,
      countInStock: 7,
      description: 'A Well Popular Shirt',
    },
    {
      name: 'Shirt',
      slug: 'free-shirt16',
      category: 'products',
      image: '/public/images/3.jpg',
      price: 70,
      brand: 'Polo',
      rating: 4.5,
      numReviews: 7,
      countInStock: 7,
      description: 'A Well Popular Shirt',
    },
  ],
}
export default data
