const data = {
  products: [
    {
      name: 'Shirt',
      slug: 'free-shirt',
      category: 'products',
      image: '/public/images/1.jpg',
      price: 70,
      brand: 'Polo',
      rating: 4.5,
      numReviews: 7,
      countInStock: 7,
      description: 'A Well Popular Shirt',
    },
    {
      name: 'Sandals',
      slug: 'free-Sandals',
      category: 'products',
      image: '/public/images/2.jpg',
      price: 70,
      brand: 'Polo',
      rating: 4.5,
      numReviews: 7,
      countInStock: 7,
      description: 'A Well Popular Sandals',
    },
    {
      name: 'Shoe',
      slug: 'free-Shoe',
      category: 'products',
      image: '/public/images/6.jpg',
      price: 70,
      brand: 'Polo',
      rating: 4.5,
      numReviews: 7,
      countInStock: 7,
      description: 'A Well Popular Shoe',
    },
    {
      name: 'Leather',
      slug: 'free-Leather',
      category: 'products',
      image: '/public/images/5.jpg',
      price: 70,
      brand: 'Polo',
      rating: 4.5,
      numReviews: 7,
      countInStock: 7,
      description: 'A Well Popular Leather',
    },
    {
      name: 'Bag',
      slug: 'free-Bag',
      category: 'products',
      image: '/public/images/6.jpg',
      price: 70,
      brand: 'Polo',
      rating: 4.5,
      numReviews: 7,
      countInStock: 7,
      description: 'A Well Popular Bag',
    },
    {
      name: 'Shirt',
      slug: 'free-shirt1',
      category: 'products',
      image: '/public/images/7.jpg',
      price: 70,
      brand: 'Polo',
      rating: 4.5,
      numReviews: 7,
      countInStock: 7,
      description: 'A Well Popular Shirt',
    },
    {
      name: 'Shirt',
      slug: 'free-shirt2',
      category: 'products',
      image: '/public/images/8.jpg',
      price: 70,
      brand: 'Polo',
      rating: 4.5,
      numReviews: 7,
      countInStock: 7,
      description: 'A Well Popular Shirt',
    },
    {
      name: 'Shirt',
      slug: 'free-shirt3',
      category: 'products',
      image: '/public/images/9.jpg',
      price: 70,
      brand: 'Polo',
      rating: 4.5,
      numReviews: 7,
      countInStock: 7,
      description: 'A Well Popular Shirt',
    },
    {
      name: 'Shirt',
      slug: 'free-shirt4',
      category: 'products',
      image: '/public/images/1.jpg',
      price: 70,
      brand: 'Polo',
      rating: 4.5,
      numReviews: 7,
      countInStock: 7,
      description: 'A Well Popular Shirt',
    },
    {
      name: 'Shirt',
      slug: 'free-shirt5',
      category: 'products',
      image: '/public/images/1.jpg',
      price: 70,
      brand: 'Polo',
      rating: 4.5,
      numReviews: 7,
      countInStock: 7,
      description: 'A Well Popular Shirt',
    },
    {
      name: 'Shirt',
      slug: 'free-shirt6',
      category: 'products',
      image: '/public/images/2.jpg',
      price: 70,
      brand: 'Polo',
      rating: 4.5,
      numReviews: 7,
      countInStock: 7,
      description: 'A Well Popular Shirt',
    },
    {
      name: 'Shirt',
      slug: 'free-shirt7',
      category: 'products',
      image: '/public/images/1.jpg',
      price: 70,
      brand: 'Polo',
      rating: 4.5,
      numReviews: 7,
      countInStock: 7,
      description: 'A Well Popular Shirt',
    },
    {
      name: 'Shirt',
      slug: 'free-shirt8',
      category: 'products',
      image: '/public/images/3.jpg',
      price: 70,
      brand: 'Polo',
      rating: 4.5,
      numReviews: 7,
      countInStock: 7,
      description: 'A Well Popular Shirt',
    },
    {
      name: 'Shirt',
      slug: 'free-shirt9',
      category: 'products',
      image: '/public/images/4.jpg',
      price: 70,
      brand: 'Polo',
      rating: 4.5,
      numReviews: 7,
      countInStock: 7,
      description: 'A Well Popular Shirt',
    },
    {
      name: 'Shirt',
      slug: 'free-shirt10',
      category: 'products',
      image: '/public/images/5.jpg',
      price: 70,
      brand: 'Polo',
      rating: 4.5,
      numReviews: 7,
      countInStock: 7,
      description: 'A Well Popular Shirt',
    },
    {
      name: 'Shirt',
      slug: 'free-shirt11',
      category: 'products',
      image: '/public/images/6.jpg',
      price: 70,
      brand: 'Polo',
      rating: 4.5,
      numReviews: 7,
      countInStock: 7,
      description: 'A Well Popular Shirt',
    },

    {
      name: 'Shirt',
      slug: 'free-shirt12',
      category: 'products',
      image: '/public/images/7.jpg',
      price: 70,
      brand: 'Polo',
      rating: 4.5,
      numReviews: 7,
      countInStock: 7,
      description: 'A Well Popular Shirt',
    },
    {
      name: 'Shirt',
      slug: 'free-shirt13',
      category: 'products',
      image: '/public/images/8.jpg',
      price: 70,
      brand: 'Polo',
      rating: 4.5,
      numReviews: 7,
      countInStock: 7,
      description: 'A Well Popular Shirt',
    },
    {
      name: 'Shirt',
      slug: 'free-shirt14',
      category: 'products',
      image: '/public/images/9.jpg',
      price: 70,
      brand: 'Polo',
      rating: 4.5,
      numReviews: 7,
      countInStock: 7,
      description: 'A Well Popular Shirt',
    },

    {
      name: 'Shirt',
      slug: 'free-shirt15',
      category: 'products',
      image: '/public/images/1.jpg',
      price: 70,
      brand: 'Polo',
      rating: 4.5,
      numReviews: 7,
      countInStock: 7,
      description: 'A Well Popular Shirt',
    },
    {
      name: 'Shirt',
      slug: 'free-shirt16',
      category: 'products',
      image: '/public/images/3.jpg',
      price: 70,
      brand: 'Polo',
      rating: 4.5,
      numReviews: 7,
      countInStock: 7,
      description: 'A Well Popular Shirt',
    },
  ],
}
export default data
